101 add firebase plugin
Cambalab/ns-vue-radio pull request #122
Opened 2019-08-26 20:43 UTC by estefi-prieto

This PR provides:
  firebase plugin
  removed console.log

Closes #101

2019-08-26 20:56 UTC, sgobotta commented on app/lib/local-api.js
> +    // console.log(id)
let's delete this bad boy

2019-08-27 14:13 UTC, sgobotta requested changes

2019-08-27 14:13 UTC, sgobotta commented on .gitignore
> +app/App_Resources/Android/google-services.json
Please change **app/App_Resources/Android/google-services.json** to just **google-services.json**. Why? Because we're asusming the file will always be in that directory. From migration to migration this path may change. Also, if we (for some reason) copy a google-services file in the root directory by accident, it won't by commited. Ignoring google-service sin all paths could help us use the file in the root when we use the building script. Anyhow, it looks safer to me to just ignore everything with **google-services.json** name.
Please remove the blank line between Firebase title and the file name, so that it matches the styling with other titles in the .gitignore

2019-08-27 14:25 UTC, estefi-prieto commented on .gitignore
> +app/App_Resources/Android/google-services.json
I thinked that .gitignore file needed the full path. I'll do it

2019-08-27 17:24 UTC, sgobotta approved these changes
Looking good!

2019-08-27 17:58 UTC, merged