Fetch information from confuguration json file
Cambalab/ns-vue-radio pull request #135
Opened 2019-09-12 13:39 UTC by estefi-prieto

This PR provides:
tool to read information from configuration file
use the configuration data from file with default values too

Closes #111

2019-09-12 15:22 UTC, sgobotta requested changes

2019-09-12 15:22 UTC, sgobotta commented on tools/create-app.bash
> +STRING_CONFIGURATION_FILE=$(jq '. | tostring' $CONFIGURATION_FILE)
if it's a string, it's not a file anymore : ) we can just use `STRINGIFIED_CONFIGURATION` as variable.

I get the tostring part of the script but, what does `jq` means?

2019-09-12 15:22 UTC, sgobotta commented on tools/create-app.bash
> +tns build android --bundle --release --env.customization=$STRING_CONFIGURATION_FILE --compileSdk 28 --key-store-path $KEYSTORE_PATH --key-store-password $KEYSTORE_PASS --key-store-alias $KEYSTORE_ALI
What do you think about using uppercase for env variables?

2019-09-12 15:22 UTC, sgobotta commented on webpack.config.js
> +                "customization": customization.split('\\').join('')
Can we use uppercase for env variables, just like the other custom variables? (TNS_ENV, API_URL)

2019-09-12 15:22 UTC, sgobotta commented on app/config.js
>    'jsondata': true,
We can avoid code repetition if we use destructuring ES6 syntax, like we did in some vue components.

2019-09-12 15:22 UTC, sgobotta commented on app/config.js
> +  'sections': customization.sections || [
Why we don't need Social and and Podcasts by default anymore?

2019-09-12 15:22 UTC, sgobotta commented on .eslintrc
> +    "customization": true
If we change it to uppercase we'd have to edit this too I  think.

2019-09-12 18:43 UTC, estefi-prieto commented on tools/create-app.bash
> +tns build android --bundle --release --env.customization=$STRING_CONFIGURATION_FILE --compileSdk 28 --key-store-path $KEYSTORE_PATH --key-store-password $KEYSTORE_PASS --key-store-alias $KEYSTORE_ALI
It's the same, but if the rest of the variables of the webpack use lowercase, we should use the same convention.

2019-09-12 19:02 UTC, estefi-prieto commented on tools/create-app.bash
> +STRING_CONFIGURATION_FILE=$(jq '. | tostring' $CONFIGURATION_FILE)
> I get the tostring part of the script but, what does jq means?

it's a command-line JSON processor.

[jq manual](https://stedolan.github.io/jq/manual/)

2019-09-12 19:41 UTC, estefi-prieto commented on webpack.config.js
> +                "customization": customization.split('\\').join('')
It was changed

2019-09-12 19:42 UTC, estefi-prieto commented on app/config.js
>    'jsondata': true,
I think the same. I changed it

2019-09-12 19:50 UTC, estefi-prieto commented on .eslintrc
> +    "customization": true
It was changed too

2019-09-13 01:55 UTC, sgobotta commented on tools/create-app.bash
> +STRING_CONFIGURATION_FILE=$(jq '. | tostring' $CONFIGURATION_FILE)
Alrighty, good to know : )

2019-09-13 01:57 UTC, sgobotta commented on tools/create-app.bash
> +tns build android --bundle --release --env.customization=$STRING_CONFIGURATION_FILE --compileSdk 28 --key-store-path $KEYSTORE_PATH --key-store-password $KEYSTORE_PASS --key-store-alias $KEYSTORE_ALI
Yes, you're right, I agree with you, let's keep the convention webpack already uses.

2019-09-13 01:58 UTC, sgobotta commented on app/config.js
> +    activeColor: navActiveColor,
loved this aliases >:D

2019-09-13 01:58 UTC, sgobotta approved these changes

2019-09-13 01:59 UTC, sgobotta commented
Nice job, good to merge!!! :tada:

2019-09-13 02:30 UTC, merged