Create radio tool: Adds a README.md
Cambalab/ns-vue-radio pull request #153
Opened 2019-10-05 20:18 UTC by sgobotta

This PR provides:

+   `README.md` with usage and bundle testing instructions

Testing instructions:

+   [ ] follow steps in `README.md`
+   [ ] get an `.aab` bundle generated
+   [ ] get an `.apks` bundle generated
+   [ ] install an application in your mobile phone

2019-10-07 13:38 UTC, FacundoMainere requested changes

2019-10-07 13:38 UTC, FacundoMainere commented on tools/README.md
> +Based on existent nativescript tools, `ns-vue-radio` provides a bash script to help building radio apps easily from the command line.
existing*

2019-10-07 13:38 UTC, FacundoMainere commented on tools/README.md
> +The script will generate a `.aab` bundle that let us build different `apks`, each one optimized for different devices. This bundle or a single `.apk` file can be used to deploy applications to the Go
we would*

2019-10-07 13:38 UTC, FacundoMainere commented on tools/README.md
> +The `.aab` bundle is used to generate many apks, each of them specifically supports different devices architecture and/or Android versions. Since every single `.apk` is built exclusively for a specif
device's architectures*

2019-10-07 14:05 UTC, sgobotta commented on tools/README.md
> +Based on existent nativescript tools, `ns-vue-radio` provides a bash script to help building radio apps easily from the command line.
existing || existent :tada:

2019-10-07 17:17 UTC, FacundoMainere approved these changes

2019-10-08 17:10 UTC, FacundoMainere commented
Perfectomundo.

2019-10-08 17:10 UTC, merged